name = "dry-term-30e8"
main = "src/index.js"
compatibility_date = "2026-04-17"

[[d1_databases]]
binding = "TELEMETRY_DB"
database_name = "agentmemory-telemetry-v2"
database_id = "3ea14047-e013-455b-80c7-b9d0628d469c"

[[send_email]]
name = "EMAIL"
destination_address = "jonsobol@gmail.com"
